### ISSUE TITLE
Import issues on Python 3

### ISSUE THREAD

**Issue by TiberiumPY** [kxgames/glooey#2]
Using Python 3.6 (same in 3.5):
```bash
sudo python3.6 setup.py install
```
Installation runs fine, but ANY example throws an error (used demo_helpers.py in this):
```
Traceback (most recent call last):
  File "demo_helpers.py", line 4, in <module>
    import glooey
  File "/usr/lib/python3.6/site-packages/glooey-0.1.0-py3.6.egg/glooey/__init__.py", line 11, in <module>
    from . import themes
ImportError: cannot import name 'themes'
```

**Comment by TiberiumPY** [comment]
Fix (works for me):
replace `from . import drawing` and `from . import themes` to:
```python
import drawing
import themes
```
