### ISSUE TITLE
Rectangle.round()

### ISSUE THREAD

**Issue by TiberiumPY** [kxgames/glooey#5]
Got a traceback:
```python
Traceback (most recent call last):
  File "demo_mouse_responsiveness.py", line 76, in <module>
    gui.add(grid)
  File "/opt/pypy3/site-packages/glooey-0.1.0-py3.5.egg/glooey/containers.py", line 47, in add
    self._repack_and_regroup_children()
  File "/opt/pypy3/site-packages/glooey-0.1.0-py3.5.egg/glooey/helpers.py", line 82, in wrapped_method
    method(self, *args, **kwargs)
  File "/opt/pypy3/site-packages/glooey-0.1.0-py3.5.egg/glooey/widget.py", line 888, in _repack_and_regroup_children
    self.repack()
  File "/opt/pypy3/site-packages/glooey-0.1.0-py3.5.egg/glooey/helpers.py", line 82, in wrapped_method
    method(self, *args, **kwargs)
  File "/opt/pypy3/site-packages/glooey-0.1.0-py3.5.egg/glooey/root.py", line 40, in repack
    self.resize(self.territory)
  File "/opt/pypy3/site-packages/glooey-0.1.0-py3.5.egg/glooey/widget.py", line 215, in resize
    self.realign()
  File "/opt/pypy3/site-packages/glooey-0.1.0-py3.5.egg/glooey/widget.py", line 237, in realign
    content_rect.round()
AttributeError: 'Rectangle' object has no attribute 'round'
```

It seems what there's no round() method of Rectangle object, but it's still called. Maybe you forgot to push it to the repository?

**Comment by kalekundert** [comment]
The Rectangle class is from the ``vecrec`` module, and I had forgotten to push it until a few days ago.  It should work if you upgrade to ``vecrec 0.3.0``:

    $ pip install --upgrade vecrec
