### ISSUE TITLE
ImportError: cannot import name 'OrderedGroup' from 'pyglet.graphics'

### ISSUE THREAD

**Issue by Torxed** [kxgames/glooey#61]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
...
  File "/home/anton/github/project/project/gui/app.py", line 2, in <module>
    import glooey
  File "/usr/lib/python3.11/site-packages/glooey/__init__.py", line 9, in <module>
    from .widget import *
  File "/usr/lib/python3.11/site-packages/glooey/widget.py", line 12, in <module>
    from glooey import drawing
  File "/usr/lib/python3.11/site-packages/glooey/drawing/__init__.py", line 4, in <module>
    from .stencil import *
  File "/usr/lib/python3.11/site-packages/glooey/drawing/stencil.py", line 4, in <module>
    from pyglet.graphics import Group, OrderedGroup
ImportError: cannot import name 'OrderedGroup' from 'pyglet.graphics' (/usr/lib/python3.11/site-packages/pyglet/graphics/__init__.py)
```

Latest version of pyglet and glooey.

**Comment by kalekundert** [comment]
This is probably because I haven't added support for pyglet 2.0 yet, see #56.

**Comment by Torxed** [comment]
Ah, that is most likely the case.
Was a few years since I was working with Pyglet, and I remember `OrderedGroup` being used so the error confused me a bit.

I'll close this as it's a duplicate.
